<link rel="stylesheet" href="/assets/css/custom.css">
title: "AI for Good Lab"
description: "Research in AI, Geometric Methods for Social Good Applications"
theme: jekyll-theme-cayman  # Or any other Jekyll theme you prefer
url: "https://ai4good.github.io"